apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  name: master
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: k8sCluster.shitlab.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 172.15.0.0/16