apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-main-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.101.10-172.16.101.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-l2advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - local-main-pool