apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: "24h0m0s"
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 20.20.20.101
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  name: master1
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
  timeoutForControlPlane: "4m0s"
  certSANs:
  - "20.20.20.100"
  - "20.20.20.101"
  - "20.20.20.102"
  - "20.20.20.103"
  - "20.20.20.104"
  - "loadbalancer"
  - "lb"
  - "master1"
  - "master2"
  - "master3"
  - "worker1"
  - "master-1"
  - "master-2"
  - "master-3"
  - "worker-1"
  - "loadbalancer.zeroCluster.lab"
  - "master1.zeroCluster.lab"
  - "master2.zeroCluster.lab"
  - "master3.zeroCluster.lab"
  - "worker1.zeroCluster.lab"
  - "master-1.zeroCluster.lab"
  - "master-2.zeroCluster.lab"
  - "master-3.zeroCluster.lab"
  - "worker-1.zeroCluster.lab"
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
etcd: {}  # Removed local and peer SANs fields
kubernetesVersion: v1.28.8
#imageRepository: registry.k8s.io
kind: ClusterConfiguration
controlPlaneEndpoint: "loadbalancer.zerocluster.lab:6443"  # Use IP address directly
networking:
  dnsDomain: zerocluster.lab
  serviceSubnet: 10.96.0.0/12
  podSubnet: 192.110.0.0/16
scheduler: {}
