---
- name: Update apt repository
  apt: update_cache=yes

- name: Install basic packages 
  apt:
    name:
      - vim
      - git
      - wget
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present