---
- name: Update apt repository
  apt: update_cache=yes

- name: Install basic packages 
  apt:
    name:
      - vim
      - git
      - wget
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present

- name: Backup current nameservers
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.bak
    backup: yes

- name: Remove old resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  
- name: Stop systemd-resolved service
  command: systemctl stop systemd-resolved && systemctl disable systemd-resolved

- name: Update resolv.conf with new nameservers
  blockinfile:
    path: /etc/resolv.conf
    block: |
      {% for ns in nameservers %}
      nameserver {{ ns }}
      {% endfor %}
    create: yes

- name: Verify changes
  command: cat /etc/resolv.conf
  register: resolv_content

- name: print resolv.conf contents
  debug:
    msg: "{{ resolv_content.stdout }}"