apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  labels:
    app: longhorn-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: http
  selector:
    app: longhorn-ui