- name: Create /opt/configs directory
  file:
    path: /opt/configs
    state: directory
    mode: '0755'

- name: Copy kubeadm_config.yaml to master Server
  copy:
    src: kubeadm_config.yaml
    dest: /opt/configs/kubeadm_config.yaml

- name: Reset Kubernetes cluster configuration
  command: kubeadm reset --force

- name: Initialize the cluster
  command: kubeadm init --config /opt/configs/kubeadm_config.yaml

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Create /opt/logs directory
  file:
    path: /opt/logs
    state: directory
    mode: '0755'

- name: Install Cilium CLI
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
  args:
    chdir: /opt/logs

- name: Deploy Cilium for pod networks
  shell: cilium install --version 1.16.0
  args:
    chdir: /opt/logs
