---
- name: Reset Kubernetes cluster configuration
  when: inventory_hostname in groups["workers"]
  command: kubeadm reset --force

- name: Get join command from control plane
  when: "'control_plane' in group_names"
  shell: kubeadm token create --print-join-command
  register: raw_command
  run_once: true

- name: Set join command fact
  when: "'control_plane' in group_names"
  set_fact:
    join_command: "{{ raw_command.stdout.strip() }}"
  run_once: true

- name: Remove existing join log file
  when: inventory_hostname in groups["workers"]
  file:
    path: /opt/logs/workers_join.log
    state: absent

- name: Create /opt/logs directory
  file:
    path: /opt/logs
    state: directory
    mode: '0755'

- name: Join workers to cluster
  shell: "{{ hostvars[groups['control_plane'][0]].join_command }} >> /opt/logs/workers_join.log"
  when: inventory_hostname in groups["workers"]
  args:
    chdir: /opt/logs
    creates: workers_join.log
  register: join_result