---
- name: Get join command from control plane and set as fact
  when: "'control_plane' in group_names"
  shell: kubeadm token create --print-join-command
  register: raw_command
  set_fact:
    join_command: "{{ raw_command.stdout.strip() }}"

- name: Join workers to cluster
  shell: "{{ hostvars[groups['control_plane'][0]].join_command }} >> /opt/logs/workers_join.log"
  when: inventory_hostname in groups["workers"]
  args:
    chdir: /opt/logs
    creates: workers_join.log