---
- name: install dependencies
  include_tasks: install_dependencies.yaml

- name: pre install configuration
  include_tasks: preinstall_configurations.yaml

- name: initialize control plane server
  when: "'control_plane' in group_names"
  include_tasks: initialize_master.yaml

- name: join workers to cluster
  include_tasks: join_workers.yaml