---
- name:  ensure swap is disabled in fstab
  replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+\s*\S+\s+swap\s+.*)$'
        replace: '# \1'

- name: Disable swap
  command: "swapoff -a"

- name: create a file for Kubernetes sysctl params
  copy:
    content: ""
    dest: /etc/sysctl.d/kubernetes.conf
    force: no

- name: configure sysctl params for Kubernetes
  lineinfile:
    path: /etc/sysctl.d/kubernetes.conf
    line: "{{ item }}"
  with_items:
    - 'net.bridge.bridge-nf-call-iptables  = 1' #Ensures that iptables can see bridged traffic.
    - 'net.ipv4.ip_forward                 = 1' #Enables packet forwarding across interfaces
    - 'net.bridge.bridge-nf-call-ip6tables = 1' #Ensures that ip6tables can see bridged traffic.
    - 'vm.max_map_count = 262144' #Increases the maximum number of memory map areas a process can have
    - 'net.core.rmem_max = 1048576' # Sets the maximum size of the receive buffer for network sockets.

- name: apply sysctl settings
  command: sysctl --system

- name: load overlay kernel module
  modprobe:
    name: overlay
    state: present

- name: load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Remove all unused packages
  apt:
    autoremove: yes
    state: present